version: "3"
services:
  app:
    build: .
    command: python -u main.py
    ports:
      - "5505:5505"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: mymongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_crawlandsearch:/data/db  # first, create a volume named: mongo_crawlandsearch and then save data to this
    ports:
      - 27021:27017

volumes:
  mongo_crawlandsearch:
    external: true

    